### ISSUE TITLE
[Question] How to change background color of animation

### ISSUE THREAD

**Issue by quangtd95** [sonaye/lottie-editor#12]
I want to change background of some animation in lottiefiles, so, when click on button customize with bodymovin, I can not find anywhere to change color of animation. For example, change from white to transparent background.  Anyone can help me? 
p/s: My English is not good. Sorry about that.

**Comment by sonaye** [comment]
This depends on the animation itself and not on the tool, some animations have their background opacity set to 0 and some are not. It is not possible to detect which element is the background, because it varies from an animation to another.

You can try finding the background element and setting its opacity to zero manually though, see https://github.com/airbnb/lottie-web/blob/master/docs/json/shapes/fill.json#L20.

Can you change the background color of the animation using the tool?
